Introduce fluent bit
planetarium/9c-infra pull request #69
Opened 2023-02-06 02:23 UTC by Atralupus

Base code: https://github.com/planetarium/9c-k8s-config/blob/main/9c-main/cwagent-fluent-bit.yaml

Previously, we were sending all container logs to cwl, regardless of their log level.
However, now we are sending logs with log level DBG to S3, and logs of other levels are being sent to cwl.

2023-02-06 02:46 UTC, sky1045 commented on common/bootstrap/templates/fluent-bit/fluent-bit-role.yaml
> +    namespace: default
seems to be not critical

2023-02-07 07:09 UTC, area363 approved these changes

2023-02-07 07:11 UTC, sky1045 requested changes

2023-02-07 07:11 UTC, sky1045 commented on common/bootstrap/templates/fluent-bit/fluent-bit.yaml
> +          value: "9c-internal-v2"
as value

2023-02-07 07:18 UTC, Atralupus commented on common/bootstrap/templates/fluent-bit/fluent-bit.yaml
> +          value: "9c-internal-v2"
🦅

2023-02-07 07:19 UTC, Atralupus commented on common/bootstrap/templates/fluent-bit/fluent-bit.yaml
> +          value: "9c-internal-v2"
done!

2023-02-07 07:21 UTC, sky1045 approved these changes

2023-02-07 07:22 UTC, merged